### ISSUE TITLE
add some styling to the navbar

### ISSUE THREAD

**Issue by Lehebax** [Lehebax/Cocktail_dictionary#11]
Currently the navbar does not look good. Please add some styling to it.

**Comment by ShivamGarg2910** [comment]
@Lehebax , please assign this to me

**Comment by Lehebax** [comment]
Hi @ShivamGarg2910 ,
I see you've made multiple contributions to this repository. While I really appreciate all your efforts, I think we should give other contributors a chance as well to contribute for more 'good first issues' for now.
Please be on the lookout for other types of issues for now. Happy coding!
