### ISSUE TITLE
Show the list of cocktails on home page

### ISSUE THREAD

**Issue by Lehebax** [Lehebax/Cocktail_dictionary#5]
Display the list of cocktails on home page.
Use the card view created in #4 to display the details of each cocktail.

**Comment by Myrfion** [comment]
Hi, could I approach this one, and would it be possible to add `hacktoberfest-accepted` label on my PR?

**Comment by Lehebax** [comment]
Hi @Myrfion sure

**Comment by Myrfion** [comment]
I need to wait till #4 would be resolved, right?

**Comment by Lehebax** [comment]
Hi @Myrfion yes, I'm afraid so.
feel free to pick up any other issue in the meantime.

**Comment by Lehebax** [comment]
Hi @Myrfion , #4 has been resolved now. Please go ahead and continue working on this.

**Comment by Myrfion** [comment]
Just tried to approach and one thing is that I got the compilation error because it was some wrong paths to components in the Home screen when I fixed them I saw that homepage alright has some cocktails list, so is this issue still active?

**Comment by Lehebax** [comment]
Hi @Myrfion ,
Apparently one of the contributors added the list view as a part of their code. Will be closing this issue now.
Feel free to pick up another one of the available issues. Thanks!
